/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.gmail.lrchfox3.fact.swing;

/**
 *
 * @author lchinchilla
 */
public class Producto extends javax.swing.JInternalFrame {

    /**
     * Creates new form Inventario
     */
    public Producto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelBase1 = new com.gmail.lrchfox3.controles.paneles.JPanelBase();
        jPanelBase2 = new com.gmail.lrchfox3.controles.paneles.JPanelBase();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.addTab("tab1", jPanelBase1);
        jTabbedPane1.addTab("tab2", jPanelBase2);

        getContentPane().add(jTabbedPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.gmail.lrchfox3.controles.paneles.JPanelBase jPanelBase1;
    private com.gmail.lrchfox3.controles.paneles.JPanelBase jPanelBase2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
